services:
  cube:
    build:
      context: .
      dockerfile: Dockerfile
    image: heartcube:latest
    container_name: heartcube
    ports:
      - "5101:4000"
      - "15432:15432"
    env_file:
      - .env
    volumes:
      - .:/cubejs/conf
    restart: unless-stopped
    networks:
      - heartcube_net

networks:
  heartcube_net:
    driver: bridge
